apiVersion: v1
kind: ConfigMap
metadata:
  name: sookmissing-config
data: 
  DB_HOST: "db-service"
  DB_PORT: "3306"
  DB_NAME: "sookmissing_db"
  ANALYZER_URL: "http://analyzer-service:8000/analyze"
  # API_URL: "http://api-service:8000/analyze-message"
  API_URL: "http://sookmissing.com/analyze-message"